[pytest]
log_file = test.log
log_file_mode = w
log_file_level = DEBUG
log_file_format = %(asctime)s - %(levelname)s - %(message)s

marker =
    system: marks tests as part of the system test suite
    unit: marks tests as part of the unit test suite
    wip: marks tests as work in progress